import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar/Navbar";
import Footer from "./components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={` ${inter.className} overflow-x-clip`} style={{
        width: "100vw",
      }}>
        {" "}
        <Navbar />
        <main className="space-y-4 max-w-[99%] md:max-w-[85%] mx-auto">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
